diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Program Files/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
pull.rebase=false
credential.helper=manager-core
credential.https://dev.azure.com.usehttppath=true
init.defaultbranch=master
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
user.name=David-Jesus
user.email=davidjesus357@gmail.com
gui.recentrepo=C:/Users/david/Documents/Análise e desenvolvimento de sistemas/5-Semestre/autenticacao_refresh_token
credential.helperselector.selected=manager-core
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
submodule.active=.
remote.upstream.url=https://github.com/David-Jesus/code_drops_authentication.git
remote.upstream.fetch=+refs/heads/*:refs/remotes/upstream/*
branch.master.remote=origin
branch.master.merge=refs/heads/master
remote.origin.url=https://github.com/David-Jesus/code_drops_authentication.git
remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
